### PR TITLE
Doc fix

### PR DESCRIPTION
**Pull request by jackctj117**
Finished Client/Server roles section, fixed some spelling errors and cleaned up trailing spaces.

### CODE REVIEW

**Review by dgarske — CHANGES_REQUESTED** [review]
Please resolve merge conflicts. I recommend using Rebase. If you haven't been through the steps to rebase they are:

1. Make sure local git master is update to date.
   a. `git checkout master`
   b. `git pull upstream master`
2. Checkout your branch and rebase
   c. `git checkout [mybranch]`
   d. `git rebase master`
3. If you get merge conflicts, resolve them the continue
   e. `git rebase --continue`
4. Force push your branch
   f. `git push -f`

**Comment by jackctj117** [comment]
> Please resolve merge conflicts. I recommend using Rebase. If you haven't been through the steps to rebase they are:
> 
> 1. Make sure local git master is update to date.
>    a. `git checkout master`
>    b. `git pull upstream master`
> 2. Checkout your branch and rebase
>    c. `git checkout [mybranch]`
>    d. `git rebase master`
> 3. If you get merge conflicts, resolve them the continue
>    e. `git rebase --continue`
> 4. Force push your branch
>    f. `git push -f`

**Comment by jackctj117** [comment]
> Please resolve merge conflicts. I recommend using Rebase. If you haven't been through the steps to rebase they are:
> 
> 1. Make sure local git master is update to date.
>    a. `git checkout master`
>    b. `git pull upstream master`
> 2. Checkout your branch and rebase
>    c. `git checkout [mybranch]`
>    d. `git rebase master`
> 3. If you get merge conflicts, resolve them the continue
>    e. `git rebase --continue`
> 4. Force push your branch
>    f. `git push -f`

I followed the command line instructions provided by GitHub and I think I fixed the merge conflict but I am not sure.

**Comment by dgarske** [comment]
> > Please resolve merge conflicts. I recommend using Rebase. If you haven't been through the steps to rebase they are:
> > 
> > 1. Make sure local git master is update to date.
> >    a. `git checkout master`
> >    b. `git pull upstream master`
> > 2. Checkout your branch and rebase
> >    c. `git checkout [mybranch]`
> >    d. `git rebase master`
> > 3. If you get merge conflicts, resolve them the continue
> >    e. `git rebase --continue`
> > 4. Force push your branch
> >    f. `git push -f`
> 
> I followed the command line instructions provided by GitHub and I think I fixed the merge conflict but I am not sure.

If you are missing upstream add it with: `git remote add upstream https://github.com/wolfSSL/wolfHSM.git`
My instructions said "master", but its "main" in this repo.

**Review by bigbrett — APPROVED** [review]

**Review by bigbrett — APPROVED** [review]

**Review by bigbrett — APPROVED** [review]

**Review by dgarske — APPROVED** [review]

**Pull request merged**
